### ISSUE TITLE
User Story #10: As a medical admin, I want to modify the selected patient's appointment details.

### ISSUE THREAD

**Issue by Razei** [VaccTrax-Project-Organization/Vacctrax#110]
- [x] Code Design of View modified appointment details #99 
- [x] Integrate all APIs for the modified appointment details #100 
- [x] Create backend API (put request modified appointment details)  #103
- [x] Update documentation #105
