### ISSUE TITLE
User Story #16: As a patient, I would like to be able to cancel upcoming vaccination if possible. 

### ISSUE THREAD

**Issue by kharakSinghkular** [VaccTrax-Project-Organization/Vacctrax#112]
- [x] Code Design of delete upcoming appointment #98 
- [x] Integrate all APIs for the cancel upcoming appointment #101 
- [x] Create backend API (delete upcoming appointment) #106
- [x] Update documentation @benjaminweymouth #108
