### ISSUE TITLE
User Story #7: As a practitioner, I would like to update which vaccine and which dose they have received.

### ISSUE THREAD

**Issue by AnmoldeepSinghGill** [VaccTrax-Project-Organization/Vacctrax#114]
- [x] Code Design of View update vaccine details #111
- [x] Integrate all APIs for the update vaccine view  #109 
- [x] Create backend API (put route) #107 
- [x] Update documentation #104
