### ISSUE TITLE
User Story #9: As a practitioner, I want to view confirmed appointments within the clinic, which are coming up.

### ISSUE THREAD

**Issue by benjaminweymouth** [VaccTrax-Project-Organization/Vacctrax#117]
- [x] Code Design of View upcoming confirmed appointments @shankarsigdel #124
- [x] Integrate all APIs for the upcoming confirmed appointment view  @asaddc #126
- [x] Create backend API (get upcoming confirmed appointments) @razei  #127
- [x] Update documentation @benjaminweymouth #129
