### ISSUE TITLE
User Story #11: As a medical admin, I want to cancel the selected patient's appointment, or decline the requested appointment.

### ISSUE THREAD

**Issue by kharakSinghkular** [VaccTrax-Project-Organization/Vacctrax#123]
- [x] Code Design of decline requested appointment details #113 
- [x] Integrate all APIs for the decline requested appointment details #115 
- [x] Create backend API (put decline requested appointment details) #116 
- [x] Update documentation #118
