### ISSUE TITLE
User Story #8: As a practitioner, I would like to view booked appointment details, and patient details.

### ISSUE THREAD

**Issue by AnmoldeepSinghGill** [VaccTrax-Project-Organization/Vacctrax#125]
- [x] Code Design of View booked appointment details #119 
- [x] Integrate all APIs for the booked appointment view #120 
- [x] Create backend API (get booked appointment details) #121
- [x] Update documentation #122
