### ISSUE TITLE
User Story #3: As a patient, I would like to view the submitted/modified appointment details

### ISSUE THREAD

**Issue by AnmoldeepSinghGill** [VaccTrax-Project-Organization/Vacctrax#135]
- [x] Code Design of View submitted/modified appointment  #128 
- [x] Integrate all APIs for the submitted/ modified appointment view  #130 
- [x] Create backend API (get requested/ modified appointment details)  #132 
- [x] Update documentation  #134
