### ISSUE TITLE
User Story #5: As a medical admin I would like to view either a requested or booked appointment's details.

### ISSUE THREAD

**Issue by benjaminweymouth** [VaccTrax-Project-Organization/Vacctrax#136]
- [x] Code Design of View requested/ booked appointment details  @mbakir2 #138
- [x] Integrate all APIs for the requested/ booked appointment view @Uplike7 #140
- [x] Create backend API (get requested/ booked appointment details)  @AlvinSJYap #141
- [x] Update documentation  @shankarsigdel #142
