### ISSUE TITLE
User Story #4: As a medical admin I want to view all appointments that are upcoming.

### ISSUE THREAD

**Issue by kharakSinghkular** [VaccTrax-Project-Organization/Vacctrax#143]
- [x] Code Design of View upcoming appointments  #131 
- [x] Integrate all APIs for the upcoming appointment view   #133 
- [x] Create backend API (get upcoming appointment details)  #137 
- [x] Update documentation  #139
