### ISSUE TITLE
User Story #17: As a patient, I would like to be able to modify appointment through a request

### ISSUE THREAD

**Issue by AnmoldeepSinghGill** [VaccTrax-Project-Organization/Vacctrax#145]
- [x] Integrate PUT route for patient appointment @shankarsigdel  #146 
- [x] Create “Request Change Appointment” Dialog box design @Razei  #147 
- [x] Update documentation for modify patient appointment request. @Uplike7  #148
- [x]  Create backend API (put request for modifying appointment details) #167
