### ISSUE TITLE
User Story #18: As a patient, I would like to register or signup in a VaccTrax Account

### ISSUE THREAD

**Issue by AnmoldeepSinghGill** [VaccTrax-Project-Organization/Vacctrax#154]
- [x] Create signup view design @Razei #153 
- [x] Create backend POST API for creating a patient @AnmoldeepSinghGill #150 
- [x] Integrate backend API with frontend @asaddc #151 
- [x] Update documentation for signing up a patient @benjaminweymouth #152
