### ISSUE TITLE
User Story #19 As a patient, I would like to be able to log in to VaccTrax with a VaccTrax Account (email)

### ISSUE THREAD

**Issue by kharakSinghkular** [VaccTrax-Project-Organization/Vacctrax#173]
- [x] Implement JWT auth with backend  @AnmoldeepSinghGill #174
- [x] Store JWT Token and patient information on frontend @mBakir2 #175  
- [x] Create Login View based on design @benjaminweymouth #176 
- [x] Update documentation for patient login @asaddc #177
