### ISSUE TITLE
User Story #20 As a practitioner, I want to be able to sign in. 

### ISSUE THREAD

**Issue by kharakSinghkular** [VaccTrax-Project-Organization/Vacctrax#178]
- [ ] Implement JWT auth with backend  @Uplike7  #179 
- [ ] Store JWT Token and practitioner information on frontend @AlvinSJYap #180 
- [ ]  Update documentation for  Practitioner Login  @mBakir2 #181
