### ISSUE TITLE
User Story #1: As a patient, I would like to be able to select the clinic, reason, and preferred date and time for an appointment.

### ISSUE THREAD

**Issue by AnmoldeepSinghGill** [VaccTrax-Project-Organization/Vacctrax#62]
- [x] Code Design of Request appointment view #63 
- [x] Integrate all APIs for the request appointment view #64 
- [x] Create backend API (post for requesting appointment) #65 
- [x] Create backend API (get clinics) #66 
- [x] Update documentation #67

**Comment by AnmoldeepSinghGill** [comment]
- [x] Code Design of Request appointment view #63 
- [x] Integrate all APIs for the request appointment view #64 
- [x] Create backend API (post for requesting appointment) #65 
- [x] Create backend API (get clinics) #66 
- [x] Update documentation #67
