### ISSUE TITLE
User Story #2: As a patient, I would like to be able to view appointments that they currently have or have had in the past.

### ISSUE THREAD

**Issue by Razei** [VaccTrax-Project-Organization/Vacctrax#76]
- [x] Code Design of View appointment #72 
- [x] Integrate API for view appointment #73 
- [x] Create backend API for getting patient appointments from database #74 
- [x] Update documentation #75

**Comment by kharakSinghkular** [comment]
@AnmoldeepSinghGill, just a test for commenting. So that you can know about any issues that I face during acceptance test.
