### ISSUE TITLE
User Story #6: As a medical admin I would like to approve or reject the viewed requested appointment.

### ISSUE THREAD

**Issue by Razei** [VaccTrax-Project-Organization/Vacctrax#81]
- [x] Code Design of View approve/ reject appointment details  #77 
- [x] Integrate all APIs for the approve/ reject appointment view #78 
- [x] Create backend API (get approve/ reject appointment details)  #79 
- [x] Update documentation  #80
