### ISSUE TITLE
User Story #12: As a government user I want to manage the approved vaccine list.

### ISSUE THREAD

**Issue by AnmoldeepSinghGill** [VaccTrax-Project-Organization/Vacctrax#93]
- [x] Code Design of approved vaccine list #85 
- [x] Integrate all APIs for the approved vaccine list  #86 
- [x] Create backend API (CRUD approved vaccine list) #88 
- [x] Update documentation #89
