### ISSUE TITLE
User Story #15: As a medical admin I want to create the appointment with the reason, and preferred date and time for an appointment.

### ISSUE THREAD

**Issue by Razei** [VaccTrax-Project-Organization/Vacctrax#97]
- [x] Code Design of book appointment  #90 
- [x] Integrate all APIs for the book appointment   #91 
- [x] Create backend API (put book appointment) #94 
- [x] Update documentation #95
